[package]
name = "actix-jwt-middleware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.9.0"
futures = "0.3.31"
jsonwebtoken = "9.3.0"
serde = { version = "1.0.210" }
